In [2]:

# Supress Warnings

import warnings
warnings.filterwarnings('ignore')

In [3]:
# Import the numpy and pandas packages

# Importing the numpy package, numpy is a package in Python used for Scientific Computing.
# It is used to perform various operations and going to play major role in analysing Movies dataset.
import numpy as np

# Importing the pandas package, pandas is a Python package providing fast, flexible, and expressive data structures
# designed to make working with “relational” or “labeled” data both easy and intuitive.
# It aims to be the fundamental high-level building block for doing practical, real world data analysis in Python.
import pandas as pd

In [4]:
#playes playing the match
matches_played = pd.read_excel('IndiaStats.xlsx', sheetname='Sheet1') 
matches_played.head(5)

,Player Name,Team,Bat_Innings,Not Outs,Runs,Bat_Avg,Balls Faced,Strike Rate,100s,50s,...,6s,Runs Given,wickets,Balls Bowled,overs bowled,Economy,Ball_Average,Bat_style,Bowl_Style,Primary
0,Dinesh Karthik,India,77,21,1738,31.0,2358,73.7,0,9,...,15,0,0,0,0,0.00,0.0,Right-Handed,No,batsman
1,MS Dhoni,India,286,81,10415,50.8,11877,87.7,10,70,...,222,0,0,0,0,0.00,0.0,Right-Handed,No,batsman
2,Rohit Sharma,India,195,31,7808,47.6,8840,88.3,22,39,...,215,515,8,593,99,5.21,64.4,Right-Handed,Off Spin,batsman-bowler
3,Virat Kohli,India,214,37,10533,59.5,11376,92.6,39,49,...,114,665,4,665,111,6.22,166.2,Right-Handed,Medium,batsman-bowler
4,Shikhar Dhawan,India,122,7,5178,45.0,5539,93.5,15,27,...,64,0,0,0,0,0.00,0.0,Left-Handed,No,batsman

In [5]:
#indian players
indian_match = matches_played[matches_played['Team'] == 'India']
indian_match.head(15)

,Player Name,Team,Bat_Innings,Not Outs,Runs,Bat_Avg,Balls Faced,Strike Rate,100s,50s,...,6s,Runs Given,wickets,Balls Bowled,overs bowled,Economy,Ball_Average,Bat_style,Bowl_Style,Primary
0,Dinesh Karthik,India,77,21,1738,31.0,2358,73.7,0,9,...,15,0,0,0,0,0.00,0.0,Right-Handed,No,batsman
1,MS Dhoni,India,286,81,10415,50.8,11877,87.7,10,70,...,222,0,0,0,0,0.00,0.0,Right-Handed,No,batsman
2,Rohit Sharma,India,195,31,7808,47.6,8840,88.3,22,39,...,215,515,8,593,99,5.21,64.4,Right-Handed,Off Spin,batsman-bowler
3,Virat Kohli,India,214,37,10533,59.5,11376,92.6,39,49,...,114,665,4,665,111,6.22,166.2,Right-Handed,Medium,batsman-bowler
4,Shikhar Dhawan,India,122,7,5178,45.0,5539,93.5,15,27,...,64,0,0,0,0,0.00,0.0,Left-Handed,No,batsman
5,Siddarth Kaul,India,2,0,1,0.5,3,33.3,0,0,...,0,179,0,162,27,6.62,0.0,Right-Handed,Medium,bowler
6,Vijay Shankar,India,1,0,45,45.0,64,70.3,0,0,...,0,78,0,96,16,4.87,0.0,Right-Handed,Medium,batsman-bowler
7,Lokesh Rahul,India,12,3,317,35.2,393,80.7,1,2,...,5,0,0,0,0,0.00,0.0,Right-Handed,No,batsman
8,Rishabh Pant,India,2,0,41,20.5,31,132.2,0,0,...,1,0,0,0,0,0.00,0.0,Left-Handed,No,batsman
9,Umesh Yadav,India,24,14,79,7.9,134,59.0,0,0,...,1,3565,106,3558,593,6.01,33.6,Right-Handed,Fast Medium,bowler
10,Yuzvendra Chahal,India,6,3,34,11.3,66,51.5,0,0,...,0,1692,71,2113,352,4.80,23.8,Right-Handed,Leg Spin,bowler
11,Jasprit Bumrah,India,6,2,11,2.8,34,32.4,0,0,...,0,1639,78,2212,369,4.44,21.0,Right-Handed,Fast Medium,bowler
12,Krunal Pandya,India,0,0,0,0.0,0,0.0,0,0,...,0,0,0,0,0,0.00,0.0,Left-Handed,Leg Spin,bowler
13,Mayank Markande,India,0,0,0,0.0,0,0.0,0,0,...,0,0,0,0,0,0.00,0.0,Right-Handed,Leg Spin,bowler

In [6]:
#Total Runs of Team India Team
total_Runs_India = sum(indian_match['Runs'])
total_Runs_India

36200

In [7]:
#Total Innings Not Out India Team
total_not_out = sum(indian_match["Not Outs"])
total_not_out

199

In [8]:
#Total Innings Played India Team
total_innings = sum(indian_match["Bat_Innings"])
total_innings

947

In [9]:
#Total Balls Faced India Team
total_ball_faced = sum(indian_match["Balls Faced"])
total_ball_faced

40715

In [10]:
#Total No 100s and 50s India Team
total_100_50 = sum(indian_match["50s"]) + sum(indian_match["100s"])
total_100_50

283

In [11]:
# total boundary runs per innings of India
total_boundary = (4*sum(indian_match["4s"])+6*sum(indian_match["6s"]))/total_innings
total_boundary

18.092925026399154

In [12]:
#Total Batting Average of Indian Team
batting_avg_india = total_Runs_India/(total_innings-total_not_out)
round(batting_avg_india,1)

48.4

In [13]:
#Total Strike Rate India Team
strike_rate_india = (total_Runs_India/total_ball_faced)*100
strike_rate_india

88.91072086454624

In [14]:
#mile stone reaaching capability India Team
mra_india =(total_100_50/total_innings)*100
mra_india

29.883843717001056

In [15]:
#total outrate of India Team
outrate_india = (total_innings-total_not_out)*100/total_ball_faced
outrate_india

1.837160751565762

In [16]:
#australia players
aus_match = matches_played[matches_played['Team'] == 'Australia']
aus_match.head(15)

,Player Name,Team,Bat_Innings,Not Outs,Runs,Bat_Avg,Balls Faced,Strike Rate,100s,50s,...,6s,Runs Given,wickets,Balls Bowled,overs bowled,Economy,Ball_Average,Bat_style,Bowl_Style,Primary
14,Shaun Marsh,Australia,62,2,2536,42.3,5165,81.9,7,13,...,33,0,0,0,0,0.00,0.0,Left-Handed,Leg Spin,batsman
15,Aaron Finch,Australia,95,1,3444,36.6,3871,89.0,11,18,...,76,137,2,158,26,5.20,68.5,Right-Handed,Leg Spin,batsman-bowler
16,Kane Richardson,Australia,8,3,45,9.0,53,84.9,0,0,...,3,854,27,935,156,5.48,33.2,Right-Handed,Fast Medium,bowler
17,Usman Khawaja,Australia,20,2,583,32.4,725,80.4,0,5,...,8,0,0,0,0,0.00,0.0,Left-Handed,Medium,batsman
18,Glenn Maxwell,Australia,81,9,2327,32.3,1913,121.6,1,16,...,74,1885,46,2020,337,5.59,41.0,Right-Handed,Off Spin,batsman-bowler
19,Jason Behrendorff,Australia,1,1,1,0.0,1,100.0,0,0,...,0,91,3,110,18,4.96,30.3,Right-Handed,Fast Medium,bowler
20,Nathan Coulter-Nile,Australia,15,5,120,12.0,157,76.4,0,0,...,2,1011,38,1130,188,5.36,29.7,Right-Handed,Fast,bowler
21,Nathan Lyon,Australia,9,6,62,20.7,64,96.9,0,0,...,2,771,18,942,157,4.91,42.8,Right-Handed,Off Spin,bowler
22,Pat Cummins,Australia,23,9,166,11.8,246,67.5,0,0,...,3,1933,65,2184,364,5.31,29.7,Right-Handed,Fast,bowler
23,Peter Handscomb,Australia,10,0,300,30.0,295,101.7,0,3,...,3,0,0,0,0,0.00,0.0,Right-Handed,No,batsman
24,Ashton Turner,Australia,0,0,0,0.0,0,0.0,0,0,...,0,0,0,0,0,0.00,0.0,Right-Handed,No,batsman
25,Adam Zampa,Australia,17,4,97,7.5,154,63.0,0,0,...,1,1582,42,1690,282,5.61,37.7,Right-Handed,Leg Spin,bowler
26,Marcus Stoinis,Australia,24,5,807,42.5,833,96.9,1,5,...,34,953,22,944,157,6.05,43.3,Right-Handed,Medium,batsman-bowler
27,Alex Carey,Australia,9,9,246,27.3,322,76.4,0,0,...,2,0,0,0,0,0.00,0.0,Left-Handed,No,batsman
28,Jhye Richardson,Australia,5,1,39,9.8,63,61.9,0,0,...,0,383,13,402,67,5.71,29.5,Right-Handed,Fast,bowler

In [17]:
#Total Runs of Australia Team
total_Runs_aus = sum(aus_match['Runs'])
total_Runs_aus

10856

In [18]:
#Total Innings Not Out Australia Team
total_not_out_aus = sum(aus_match["Not Outs"])
total_not_out_aus

58

In [19]:
#Total Innings Played Australia Team
total_innings_aus = sum(aus_match["Bat_Innings"])
total_innings_aus

383

In [20]:
#Total Balls Faced Australia Team
total_ball_faced_aus = sum(aus_match["Balls Faced"])
total_ball_faced_aus

13961

In [21]:
#Total No 100s and 50s Australia Team
total_100_50_aus = sum(aus_match["50s"]) + sum(aus_match["100s"])
total_100_50_aus

80

In [22]:
# total boundary runs per innings of Australia Team
total_boundary_aus = (4*sum(aus_match["4s"])+6*sum(aus_match["6s"]))/total_innings_aus
total_boundary_aus

14.475195822454308

In [23]:
#Total Batting Average of Australia Team
batting_avg_aus = total_Runs_aus/(total_innings_aus-total_not_out_aus)
round(batting_avg_aus,1)

33.4

In [24]:
#Total Strike Rate Australia Team
strike_rate_aus = (total_Runs_aus/total_ball_faced_aus)*100
strike_rate_aus

77.75947281713344

In [25]:
#mile stone reaaching capability Australia Team
mra_aus =(total_100_50_aus/total_innings_aus)*100
mra_aus

20.887728459530024

In [26]:
#total outrate of Australia Team
outrate_aus = (total_innings_aus-total_not_out_aus)*100/total_ball_faced_aus
outrate_aus

2.3279134732469022

In [27]:
#previous matches played
previous_matches = pd.read_excel('IndiaVsAus.xlsx', sheetname='Sheet1') 
previous_matches.head(5)

   Id  innings city_ground  score winner
0   1        2       Delhi    172   lost
1   2        1   Ahmedabad    206   lost
2   3        1      Indore    235   lost
3   4        2      Jaipur    251    won
4   5        1    Srinagar    222   lost

In [28]:
#India Bowlers
bowler = matches_played[(matches_played['Primary'] == "bowler") | (matches_played['Primary'] == "batsman-bowler")]
india_bowler = bowler[matches_played['Team'] == "India"]
aus_bowler = bowler[matches_played['Team'] == "Australia"]
print(india_bowler)
print(aus_bowler)

         Player Name   Team  Bat_Innings  Not Outs   Runs  Bat_Avg  \
2       Rohit Sharma  India          195        31   7808     47.6
3        Virat Kohli  India          214        37  10533     59.5
5      Siddarth Kaul  India            2         0      1      0.5
6      Vijay Shankar  India            1         0     45     45.0
9        Umesh Yadav  India           24        14     79      7.9
10  Yuzvendra Chahal  India            6         3     34     11.3
11    Jasprit Bumrah  India            6         2     11      2.8
12     Krunal Pandya  India            0         0      0      0.0
13   Mayank Markande  India            0         0      0      0.0

    Balls Faced  Strike Rate  100s  50s       ...         6s  Runs Given  \
2          8840         88.3    22   39       ...        215         515
3         11376         92.6    39   49       ...        114         665
5             3         33.3     0    0       ...          0         179
6            64         70.3     0    0       ...          0          78
9           134         59.0     0    0       ...          1        3565
10           66         51.5     0    0       ...          0        1692
11           34         32.4     0    0       ...          0        1639
12            0          0.0     0    0       ...          0           0
13            0          0.0     0    0       ...          0           0

    wickets  Balls Bowled  overs bowled  Economy  Ball_Average     Bat_style  \
2         8           593            99     5.21          64.4  Right-Handed
3         4           665           111     6.22         166.2  Right-Handed
5         0           162            27     6.62           0.0  Right-Handed
6         0            96            16     4.87           0.0  Right-Handed
9       106          3558           593     6.01          33.6  Right-Handed
10       71          2113           352     4.80          23.8  Right-Handed
11       78          2212           369     4.44          21.0  Right-Handed
12        0             0             0     0.00           0.0   Left-Handed
13        0             0             0     0.00           0.0  Right-Handed

     Bowl_Style         Primary
2      Off Spin  batsman-bowler
3       Medium   batsman-bowler
5       Medium           bowler
6       Medium   batsman-bowler
9   Fast Medium          bowler
10     Leg Spin          bowler
11  Fast Medium          bowler
12     Leg Spin          bowler
13     Leg Spin          bowler

[9 rows x 21 columns]
            Player Name       Team  Bat_Innings  Not Outs  Runs  Bat_Avg  \
15          Aaron Finch  Australia           95         1  3444     36.6
16      Kane Richardson  Australia            8         3    45      9.0
18        Glenn Maxwell  Australia           81         9  2327     32.3
19    Jason Behrendorff  Australia            1         1     1      0.0
20  Nathan Coulter-Nile  Australia           15         5   120     12.0
21          Nathan Lyon  Australia            9         6    62     20.7
22          Pat Cummins  Australia           23         9   166     11.8
25           Adam Zampa  Australia           17         4    97      7.5
26       Marcus Stoinis  Australia           24         5   807     42.5
28      Jhye Richardson  Australia            5         1    39      9.8
29         D Arcy Short  Australia            4         1    83     27.7

    Balls Faced  Strike Rate  100s  50s       ...        6s  Runs Given  \
15         3871         89.0    11   18       ...        76         137
16           53         84.9     0    0       ...         3         854
18         1913        121.6     1   16       ...        74        1885
19            1        100.0     0    0       ...         0          91
20          157         76.4     0    0       ...         2        1011
21           64         96.9     0    0       ...         2         771
22          246         67.5     0    0       ...         3        1933
25          154         63.0     0    0       ...         1        1582
26          833         96.9     1    5       ...        34         953
28           63         61.9     0    0       ...         0         383
29           99         83.8     0    0       ...         1          59

    wickets  Balls Bowled  overs bowled  Economy  Ball_Average     Bat_style  \
15        2           158            26     5.20          68.5  Right-Handed
16       27           935           156     5.48          33.2  Right-Handed
18       46          2020           337     5.59          41.0  Right-Handed
19        3           110            18     4.96          30.3  Right-Handed
20       38          1130           188     5.36          29.7  Right-Handed
21       18           942           157     4.91          42.8  Right-Handed
22       65          2184           364     5.31          29.7  Right-Handed
25       42          1690           282     5.61          37.7  Right-Handed
26       22           944           157     6.05          43.3  Right-Handed
28       13           402            67     5.71          29.5  Right-Handed
29        0            42             7     7.62          61.0   Left-Handed

     Bowl_Style         Primary
15     Leg Spin  batsman-bowler
16  Fast Medium          bowler
18     Off Spin  batsman-bowler
19  Fast Medium          bowler
20        Fast           bowler
21     Off Spin          bowler
22        Fast           bowler
25     Leg Spin          bowler
26      Medium   batsman-bowler
28         Fast          bowler
29     Off Spin  batsman-bowler

[11 rows x 21 columns]

In [29]:
#balling average
runs_conceled_ind = sum(india_bowler['Runs Given'])
runs_conceled_aus = sum(aus_bowler['Runs Given'])
print(runs_conceled_ind)
print(runs_conceled_aus)

8333
9659

In [30]:
#bowls bowled
bowls_ind = sum(india_bowler['Balls Bowled'])
bowls_aus = sum(aus_bowler['Balls Bowled'])
print(bowls_ind)
print(bowls_aus)

9399
10557

In [31]:
# wickets taken
wicket_ind = sum(india_bowler['wickets'])
wicket_aus = sum(aus_bowler['wickets'])
print(wicket_ind)
print(wicket_aus)

267
276

In [32]:
# overs bowled
over_bowl_ind = sum(india_bowler['overs bowled'])
over_bowl_aus = sum(aus_bowler['overs bowled'])
print(over_bowl_ind)
print(over_bowl_aus)

1567
1759

In [33]:
#Bowl avg per wicket
ba_india = runs_conceled_ind/wicket_ind
ba_aus = runs_conceled_aus/wicket_aus
print(ba_india)
print(ba_aus)

31.209737827715355
34.9963768115942

In [34]:
#Bowl strike rate
bsr_india = over_bowl_ind/wicket_ind
bsr_aus = over_bowl_aus/wicket_aus
print(bsr_india)
print(bsr_aus)

5.868913857677903
6.3731884057971016

In [35]:
#bowler economy
be_india = runs_conceled_ind/over_bowl_ind
be_aus = runs_conceled_aus/over_bowl_aus
print(be_india)
print(be_aus)

5.317804722399489
5.491188175099488

In [36]:
#outrate bowler
ob_ind = wicket_ind/bowls_ind
ob_aus = wicket_aus/bowls_aus
print(ob_ind)
print(ob_aus)

0.02840727736993297
0.026143790849673203

In [37]:
#Condidering the Matches to be Played in Hydrabad
#total previous matches played at Hydrabad
matches_played_Hydrabad = previous_matches[previous_matches["city_ground"] == "Hyderabad"]
matches_played_Hydrabad

    Id  innings city_ground  score winner
28  29        2   Hyderabad    243   lost
37  38        2   Hyderabad    347   lost

In [38]:
#Considering the Match to be Played at Hydrabad
#Considering the things with pointer sysytem
batting_avg_india > batting_avg_aus # +1 India
strike_rate_india > strike_rate_aus # +1 India
mra_india > mra_aus # +1 India
outrate_aus > outrate_india # +1 India
#considering the previous matches at hydrbad
#if india playes second innings there are great chances of India loosing so +1 Australia
#Consdering the Ballers work
ba_india < ba_aus # +1 India
bsr_india < bsr_aus # +1 India
be_india == be_aus # economy is same
ob_ind > ob_aus # +1 India

#India has weekness to fast bowling so there are 3 fast bowler for Australia so +1 for it
#Australia has more than 2 left hand bats man and india has no professional bowler so +1 for it

#Total of India is 7
#Total of Australia is 2 and if india bats for the second innings then +1 for it
#Still the Value of Indian Team is much more than Australia

#India will Win

True

In [39]:
#Condidering the Matches to be Played in Nagpur
#total previous matches played at Nagpur
matches_played_Nagpur = previous_matches[previous_matches["city_ground"] == "Nagpur"]
matches_played_Nagpur

    Id  innings city_ground  score winner
31  32        2      Nagpur    299   lost
34  35        1      Nagpur    354    won
44  45        2      Nagpur    351    won
50  51        2      Nagpur    243    won

In [40]:
#Considering the Match to be Played at Nagpur
#Considering the things with pointer sysytem
batting_avg_india > batting_avg_aus # +1 India
strike_rate_india > strike_rate_aus # +1 India
mra_india > mra_aus # +1 India
outrate_aus > outrate_india # +1 India
#Consdering the Ballers work
ba_india < ba_aus # +1 India
bsr_india < bsr_aus # +1 India
be_india == be_aus # economy is same
ob_ind > ob_aus # +1 India

#India has weekness to fast bowling so there are 3 fast bowler for Australia so +1 for it
#Australia has more than 2 left hand bats man and india has no professional off spin bowler so +1 for it

#previous records if taken into account
#India won last of the 3 matches from 4 so probability of India win is more so +1

#Total of India is 8
#Total of Australia is 2
#Still the Value of Indian Team is much more than Australia

#India will win

True

In [41]:
#Condidering the Matches to be Played in Ranchi
#total previous matches played at Ranchi
matches_played_Ranchi = previous_matches[previous_matches["city_ground"] == "Ranchi"]
matches_played_Ranchi

Empty DataFrame
Columns: [Id, innings, city_ground, score, winner]
Index: []

In [42]:
#Considering the Match to be Played at Ranchi
#Considering the things with pointer sysytem
batting_avg_india > batting_avg_aus # +1 India
strike_rate_india > strike_rate_aus # +1 India
mra_india > mra_aus # +1 India
outrate_aus > outrate_india # +1 India
#Consdering the Ballers work
ba_india < ba_aus # +1 India
bsr_india < bsr_aus # +1 India
be_india == be_aus # economy is same
ob_ind > ob_aus # +1 India

#India has weekness to fast bowling so there are 3 fast bowler for Australia so +1 for it
#Australia has more than 2 left hand bats man and india has no professional off spin bowler so +1 for it

#previous records if taken into account
#There are no matches played here

#Total of India is 7
#Total of Australia is 2
#Still the Value of Indian Team is much more than Australia

#India will win

True

In [43]:
#Condidering the Matches to be Played in Mohali
#total previous matches played at Mohali
matches_played_Mohali = previous_matches[previous_matches["city_ground"] == "Mohali"]
matches_played_Mohali

    Id  innings city_ground  score winner
13  14        1      Mohali    289    won
26  27        1      Mohali    249   lost
36  37        2      Mohali    226   lost
43  44        1      Mohali    303   lost

In [44]:
#Considering the Match to be Played at Mohali
#Considering the things with pointer sysytem
batting_avg_india > batting_avg_aus # +1 India
strike_rate_india > strike_rate_aus # +1 India
mra_india > mra_aus # +1 India
outrate_aus > outrate_india # +1 India
#Consdering the Ballers work
ba_india < ba_aus # +1 India
bsr_india < bsr_aus # +1 India
be_india == be_aus # economy is same
ob_ind > ob_aus # +1 India

#India has weekness to fast bowling so there are 3 fast bowler for Australia so +1 for it
#Australia has more than 2 left hand bats man and india has no professional off spin bowler so +1 for it

#previous records if taken into account
#There are 4 matches played out of which 3 are won by Australia so +1 for them

#Total of India is 7
#Total of Australia is 3
#Still the Value of Indian Team is much more than Australia

#India will win

True

In [45]:
#Condidering the Matches to be Played in Delhi
#total previous matches played at Delhi
matches_played_Delhi = previous_matches[previous_matches["city_ground"] == "Delhi"]
matches_played_Delhi

    Id  innings city_ground  score winner
0    1        2       Delhi    172   lost
5    6        2       Delhi    242    won
9   10        1       Delhi    289    won
16  17        1       Delhi    227   lost
35  36        2       Delhi    230    won

In [46]:
#Considering the Match to be Played at Mohali
#Considering the things with pointer sysytem
batting_avg_india > batting_avg_aus # +1 India
strike_rate_india > strike_rate_aus # +1 India
mra_india > mra_aus # +1 India
outrate_aus > outrate_india # +1 India
#Consdering the Ballers work
ba_india < ba_aus # +1 India
bsr_india < bsr_aus # +1 India
be_india == be_aus # economy is same
ob_ind > ob_aus # +1 India

#India has weekness to fast bowling so there are 3 fast bowler for Australia so +1 for it
#Australia has more than 2 left hand bats man and india has no professional off spin bowler so +1 for it

#previous records if taken into account
#There are 5 matches played out of which 3 are won by India so +1 for them

#Total of India is 8
#Total of Australia is 2
#Still the Value of Indian Team is much more than Australia

#India will win

True

In [65]:
matches_played

,Player Name,Team,Bat_Innings,Not Outs,Runs,Bat_Avg,Balls Faced,Strike Rate,100s,50s,...,6s,Runs Given,wickets,Balls Bowled,overs bowled,Economy,Ball_Average,Bat_style,Bowl_Style,Primary
0,Dinesh Karthik,India,77,21,1738,31.0,2358,73.7,0,9,...,15,0,0,0,0,0.00,0.0,Right-Handed,No,batsman
1,MS Dhoni,India,286,81,10415,50.8,11877,87.7,10,70,...,222,0,0,0,0,0.00,0.0,Right-Handed,No,batsman
2,Rohit Sharma,India,195,31,7808,47.6,8840,88.3,22,39,...,215,515,8,593,99,5.21,64.4,Right-Handed,Off Spin,batsman-bowler
3,Virat Kohli,India,214,37,10533,59.5,11376,92.6,39,49,...,114,665,4,665,111,6.22,166.2,Right-Handed,Medium,batsman-bowler
4,Shikhar Dhawan,India,122,7,5178,45.0,5539,93.5,15,27,...,64,0,0,0,0,0.00,0.0,Left-Handed,No,batsman
5,Siddarth Kaul,India,2,0,1,0.5,3,33.3,0,0,...,0,179,0,162,27,6.62,0.0,Right-Handed,Medium,bowler
6,Vijay Shankar,India,1,0,45,45.0,64,70.3,0,0,...,0,78,0,96,16,4.87,0.0,Right-Handed,Medium,batsman-bowler
7,Lokesh Rahul,India,12,3,317,35.2,393,80.7,1,2,...,5,0,0,0,0,0.00,0.0,Right-Handed,No,batsman
8,Rishabh Pant,India,2,0,41,20.5,31,132.2,0,0,...,1,0,0,0,0,0.00,0.0,Left-Handed,No,batsman
9,Umesh Yadav,India,24,14,79,7.9,134,59.0,0,0,...,1,3565,106,3558,593,6.01,33.6,Right-Handed,Fast Medium,bowler
10,Yuzvendra Chahal,India,6,3,34,11.3,66,51.5,0,0,...,0,1692,71,2113,352,4.80,23.8,Right-Handed,Leg Spin,bowler
11,Jasprit Bumrah,India,6,2,11,2.8,34,32.4,0,0,...,0,1639,78,2212,369,4.44,21.0,Right-Handed,Fast Medium,bowler
12,Krunal Pandya,India,0,0,0,0.0,0,0.0,0,0,...,0,0,0,0,0,0.00,0.0,Left-Handed,Leg Spin,bowler
13,Mayank Markande,India,0,0,0,0.0,0,0.0,0,0,...,0,0,0,0,0,0.00,0.0,Right-Handed,Leg Spin,bowler
14,Shaun Marsh,Australia,62,2,2536,42.3,5165,81.9,7,13,...,33,0,0,0,0,0.00,0.0,Left-Handed,Leg Spin,batsman
15,Aaron Finch,Australia,95,1,3444,36.6,3871,89.0,11,18,...,76,137,2,158,26,5.20,68.5,Right-Handed,Leg Spin,batsman-bowler
16,Kane Richardson,Australia,8,3,45,9.0,53,84.9,0,0,...,3,854,27,935,156,5.48,33.2,Right-Handed,Fast Medium,bowler
17,Usman Khawaja,Australia,20,2,583,32.4,725,80.4,0,5,...,8,0,0,0,0,0.00,0.0,Left-Handed,Medium,batsman
18,Glenn Maxwell,Australia,81,9,2327,32.3,1913,121.6,1,16,...,74,1885,46,2020,337,5.59,41.0,Right-Handed,Off Spin,batsman-bowler
19,Jason Behrendorff,Australia,1,1,1,0.0,1,100.0,0,0,...,0,91,3,110,18,4.96,30.3,Right-Handed,Fast Medium,bowler
20,Nathan Coulter-Nile,Australia,15,5,120,12.0,157,76.4,0,0,...,2,1011,38,1130,188,5.36,29.7,Right-Handed,Fast,bowler
21,Nathan Lyon,Australia,9,6,62,20.7,64,96.9,0,0,...,2,771,18,942,157,4.91,42.8,Right-Handed,Off Spin,bowler
22,Pat Cummins,Australia,23,9,166,11.8,246,67.5,0,0,...,3,1933,65,2184,364,5.31,29.7,Right-Handed,Fast,bowler
23,Peter Handscomb,Australia,10,0,300,30.0,295,101.7,0,3,...,3,0,0,0,0,0.00,0.0,Right-Handed,No,batsman
24,Ashton Turner,Australia,0,0,0,0.0,0,0.0,0,0,...,0,0,0,0,0,0.00,0.0,Right-Handed,No,batsman
25,Adam Zampa,Australia,17,4,97,7.5,154,63.0,0,0,...,1,1582,42,1690,282,5.61,37.7,Right-Handed,Leg Spin,bowler
26,Marcus Stoinis,Australia,24,5,807,42.5,833,96.9,1,5,...,34,953,22,944,157,6.05,43.3,Right-Handed,Medium,batsman-bowler
27,Alex Carey,Australia,9,9,246,27.3,322,76.4,0,0,...,2,0,0,0,0,0.00,0.0,Left-Handed,No,batsman
28,Jhye Richardson,Australia,5,1,39,9.8,63,61.9,0,0,...,0,383,13,402,67,5.71,29.5,Right-Handed,Fast,bowler
29,D Arcy Short,Australia,4,1,83,27.7,99,83.8,0,0,...,1,59,0,42,7,7.62,61.0,Left-Handed,Off Spin,batsman-bowler

In [48]:
#By more runs

runs = matches_played.Runs.sort_values(ascending = False).head(5)
matches_played.iloc[runs.index]

,Player Name,Team,Bat_Innings,Not Outs,Runs,Bat_Avg,Balls Faced,Strike Rate,100s,50s,...,6s,Runs Given,wickets,Balls Bowled,overs bowled,Economy,Ball_Average,Bat_style,Bowl_Style,Primary
3,Virat Kohli,India,214,37,10533,59.5,11376,92.6,39,49,...,114,665,4,665,111,6.22,166.2,Right-Handed,Medium,batsman-bowler
1,MS Dhoni,India,286,81,10415,50.8,11877,87.7,10,70,...,222,0,0,0,0,0.00,0.0,Right-Handed,No,batsman
2,Rohit Sharma,India,195,31,7808,47.6,8840,88.3,22,39,...,215,515,8,593,99,5.21,64.4,Right-Handed,Off Spin,batsman-bowler
4,Shikhar Dhawan,India,122,7,5178,45.0,5539,93.5,15,27,...,64,0,0,0,0,0.00,0.0,Left-Handed,No,batsman
15,Aaron Finch,Australia,95,1,3444,36.6,3871,89.0,11,18,...,76,137,2,158,26,5.20,68.5,Right-Handed,Leg Spin,batsman-bowler

In [51]:
#runs by bat_innings and min of 50 innings

runsbymat = matches_played[matches_played.Bat_Innings >=  20].Runs/matches_played[matches_played.Bat_Innings >= 50].Bat_Innings
runsbymat = runsbymat.sort_values(ascending = False).head(10)
matches_played.iloc[runsbymat.index]

,Player Name,Team,Bat_Innings,Not Outs,Runs,Bat_Avg,Balls Faced,Strike Rate,100s,50s,...,6s,Runs Given,wickets,Balls Bowled,overs bowled,Economy,Ball_Average,Bat_style,Bowl_Style,Primary
3,Virat Kohli,India,214,37,10533,59.5,11376,92.6,39,49,...,114,665,4,665,111,6.22,166.2,Right-Handed,Medium,batsman-bowler
4,Shikhar Dhawan,India,122,7,5178,45.0,5539,93.5,15,27,...,64,0,0,0,0,0.00,0.0,Left-Handed,No,batsman
14,Shaun Marsh,Australia,62,2,2536,42.3,5165,81.9,7,13,...,33,0,0,0,0,0.00,0.0,Left-Handed,Leg Spin,batsman
2,Rohit Sharma,India,195,31,7808,47.6,8840,88.3,22,39,...,215,515,8,593,99,5.21,64.4,Right-Handed,Off Spin,batsman-bowler
1,MS Dhoni,India,286,81,10415,50.8,11877,87.7,10,70,...,222,0,0,0,0,0.00,0.0,Right-Handed,No,batsman
15,Aaron Finch,Australia,95,1,3444,36.6,3871,89.0,11,18,...,76,137,2,158,26,5.20,68.5,Right-Handed,Leg Spin,batsman-bowler
18,Glenn Maxwell,Australia,81,9,2327,32.3,1913,121.6,1,16,...,74,1885,46,2020,337,5.59,41.0,Right-Handed,Off Spin,batsman-bowler
0,Dinesh Karthik,India,77,21,1738,31.0,2358,73.7,0,9,...,15,0,0,0,0,0.00,0.0,Right-Handed,No,batsman
9,Umesh Yadav,India,24,14,79,7.9,134,59.0,0,0,...,1,3565,106,3558,593,6.01,33.6,Right-Handed,Fast Medium,bowler
17,Usman Khawaja,Australia,20,2,583,32.4,725,80.4,0,5,...,8,0,0,0,0,0.00,0.0,Left-Handed,Medium,batsman

In [52]:
strkrt_player = matches_played[matches_played.Bat_Innings >=  50]['Strike Rate'].sort_values(ascending = False).head(10)
matches_played.iloc[strkrt_player.index]

,Player Name,Team,Bat_Innings,Not Outs,Runs,Bat_Avg,Balls Faced,Strike Rate,100s,50s,...,6s,Runs Given,wickets,Balls Bowled,overs bowled,Economy,Ball_Average,Bat_style,Bowl_Style,Primary
18,Glenn Maxwell,Australia,81,9,2327,32.3,1913,121.6,1,16,...,74,1885,46,2020,337,5.59,41.0,Right-Handed,Off Spin,batsman-bowler
4,Shikhar Dhawan,India,122,7,5178,45.0,5539,93.5,15,27,...,64,0,0,0,0,0.00,0.0,Left-Handed,No,batsman
3,Virat Kohli,India,214,37,10533,59.5,11376,92.6,39,49,...,114,665,4,665,111,6.22,166.2,Right-Handed,Medium,batsman-bowler
15,Aaron Finch,Australia,95,1,3444,36.6,3871,89.0,11,18,...,76,137,2,158,26,5.20,68.5,Right-Handed,Leg Spin,batsman-bowler
2,Rohit Sharma,India,195,31,7808,47.6,8840,88.3,22,39,...,215,515,8,593,99,5.21,64.4,Right-Handed,Off Spin,batsman-bowler
1,MS Dhoni,India,286,81,10415,50.8,11877,87.7,10,70,...,222,0,0,0,0,0.00,0.0,Right-Handed,No,batsman
14,Shaun Marsh,Australia,62,2,2536,42.3,5165,81.9,7,13,...,33,0,0,0,0,0.00,0.0,Left-Handed,Leg Spin,batsman
0,Dinesh Karthik,India,77,21,1738,31.0,2358,73.7,0,9,...,15,0,0,0,0,0.00,0.0,Right-Handed,No,batsman

#### Bowling

In [55]:
#WICKETS ANALYSIS

wkts = matches_played.wickets.sort_values(ascending = False).head(10)
matches_played.iloc[wkts.index]

,Player Name,Team,Bat_Innings,Not Outs,Runs,Bat_Avg,Balls Faced,Strike Rate,100s,50s,...,6s,Runs Given,wickets,Balls Bowled,overs bowled,Economy,Ball_Average,Bat_style,Bowl_Style,Primary
9,Umesh Yadav,India,24,14,79,7.9,134,59.0,0,0,...,1,3565,106,3558,593,6.01,33.6,Right-Handed,Fast Medium,bowler
11,Jasprit Bumrah,India,6,2,11,2.8,34,32.4,0,0,...,0,1639,78,2212,369,4.44,21.0,Right-Handed,Fast Medium,bowler
10,Yuzvendra Chahal,India,6,3,34,11.3,66,51.5,0,0,...,0,1692,71,2113,352,4.80,23.8,Right-Handed,Leg Spin,bowler
22,Pat Cummins,Australia,23,9,166,11.8,246,67.5,0,0,...,3,1933,65,2184,364,5.31,29.7,Right-Handed,Fast,bowler
18,Glenn Maxwell,Australia,81,9,2327,32.3,1913,121.6,1,16,...,74,1885,46,2020,337,5.59,41.0,Right-Handed,Off Spin,batsman-bowler
25,Adam Zampa,Australia,17,4,97,7.5,154,63.0,0,0,...,1,1582,42,1690,282,5.61,37.7,Right-Handed,Leg Spin,bowler
20,Nathan Coulter-Nile,Australia,15,5,120,12.0,157,76.4,0,0,...,2,1011,38,1130,188,5.36,29.7,Right-Handed,Fast,bowler
16,Kane Richardson,Australia,8,3,45,9.0,53,84.9,0,0,...,3,854,27,935,156,5.48,33.2,Right-Handed,Fast Medium,bowler
26,Marcus Stoinis,Australia,24,5,807,42.5,833,96.9,1,5,...,34,953,22,944,157,6.05,43.3,Right-Handed,Medium,batsman-bowler
21,Nathan Lyon,Australia,9,6,62,20.7,64,96.9,0,0,...,2,771,18,942,157,4.91,42.8,Right-Handed,Off Spin,bowler

In [59]:
#wickets by match

wktsbymat = matches_played.wickets/matches_played['Balls Bowled']
wktsbymat = wktsbymat.sort_values(ascending = False).head(10)

matches_played.iloc[wktsbymat.index]

,Player Name,Team,Bat_Innings,Not Outs,Runs,Bat_Avg,Balls Faced,Strike Rate,100s,50s,...,6s,Runs Given,wickets,Balls Bowled,overs bowled,Economy,Ball_Average,Bat_style,Bowl_Style,Primary
11,Jasprit Bumrah,India,6,2,11,2.8,34,32.4,0,0,...,0,1639,78,2212,369,4.44,21.0,Right-Handed,Fast Medium,bowler
20,Nathan Coulter-Nile,Australia,15,5,120,12.0,157,76.4,0,0,...,2,1011,38,1130,188,5.36,29.7,Right-Handed,Fast,bowler
10,Yuzvendra Chahal,India,6,3,34,11.3,66,51.5,0,0,...,0,1692,71,2113,352,4.80,23.8,Right-Handed,Leg Spin,bowler
28,Jhye Richardson,Australia,5,1,39,9.8,63,61.9,0,0,...,0,383,13,402,67,5.71,29.5,Right-Handed,Fast,bowler
9,Umesh Yadav,India,24,14,79,7.9,134,59.0,0,0,...,1,3565,106,3558,593,6.01,33.6,Right-Handed,Fast Medium,bowler
22,Pat Cummins,Australia,23,9,166,11.8,246,67.5,0,0,...,3,1933,65,2184,364,5.31,29.7,Right-Handed,Fast,bowler
16,Kane Richardson,Australia,8,3,45,9.0,53,84.9,0,0,...,3,854,27,935,156,5.48,33.2,Right-Handed,Fast Medium,bowler
19,Jason Behrendorff,Australia,1,1,1,0.0,1,100.0,0,0,...,0,91,3,110,18,4.96,30.3,Right-Handed,Fast Medium,bowler
25,Adam Zampa,Australia,17,4,97,7.5,154,63.0,0,0,...,1,1582,42,1690,282,5.61,37.7,Right-Handed,Leg Spin,bowler
26,Marcus Stoinis,Australia,24,5,807,42.5,833,96.9,1,5,...,34,953,22,944,157,6.05,43.3,Right-Handed,Medium,batsman-bowler

In [61]:
#Economy wise

economy = matches_played[matches_played['wickets'] >= 50].Economy.sort_values(ascending = True).head(10)
matches_played.iloc[economy.index]

,Player Name,Team,Bat_Innings,Not Outs,Runs,Bat_Avg,Balls Faced,Strike Rate,100s,50s,...,6s,Runs Given,wickets,Balls Bowled,overs bowled,Economy,Ball_Average,Bat_style,Bowl_Style,Primary
11,Jasprit Bumrah,India,6,2,11,2.8,34,32.4,0,0,...,0,1639,78,2212,369,4.44,21.0,Right-Handed,Fast Medium,bowler
10,Yuzvendra Chahal,India,6,3,34,11.3,66,51.5,0,0,...,0,1692,71,2113,352,4.80,23.8,Right-Handed,Leg Spin,bowler
22,Pat Cummins,Australia,23,9,166,11.8,246,67.5,0,0,...,3,1933,65,2184,364,5.31,29.7,Right-Handed,Fast,bowler
9,Umesh Yadav,India,24,14,79,7.9,134,59.0,0,0,...,1,3565,106,3558,593,6.01,33.6,Right-Handed,Fast Medium,bowler

#### 4's and 6's

In [65]:
#maximum fours

fours = matches_played['4s'].sort_values(ascending = False).head(10)
matches_played.iloc[fours.index]

,Player Name,Team,Bat_Innings,Not Outs,Runs,Bat_Avg,Balls Faced,Strike Rate,100s,50s,...,6s,Runs Given,wickets,Balls Bowled,overs bowled,Economy,Ball_Average,Bat_style,Bowl_Style,Primary
3,Virat Kohli,India,214,37,10533,59.5,11376,92.6,39,49,...,114,665,4,665,111,6.22,166.2,Right-Handed,Medium,batsman-bowler
1,MS Dhoni,India,286,81,10415,50.8,11877,87.7,10,70,...,222,0,0,0,0,0.00,0.0,Right-Handed,No,batsman
2,Rohit Sharma,India,195,31,7808,47.6,8840,88.3,22,39,...,215,515,8,593,99,5.21,64.4,Right-Handed,Off Spin,batsman-bowler
4,Shikhar Dhawan,India,122,7,5178,45.0,5539,93.5,15,27,...,64,0,0,0,0,0.00,0.0,Left-Handed,No,batsman
15,Aaron Finch,Australia,95,1,3444,36.6,3871,89.0,11,18,...,76,137,2,158,26,5.20,68.5,Right-Handed,Leg Spin,batsman-bowler
18,Glenn Maxwell,Australia,81,9,2327,32.3,1913,121.6,1,16,...,74,1885,46,2020,337,5.59,41.0,Right-Handed,Off Spin,batsman-bowler
14,Shaun Marsh,Australia,62,2,2536,42.3,5165,81.9,7,13,...,33,0,0,0,0,0.00,0.0,Left-Handed,Leg Spin,batsman
0,Dinesh Karthik,India,77,21,1738,31.0,2358,73.7,0,9,...,15,0,0,0,0,0.00,0.0,Right-Handed,No,batsman
26,Marcus Stoinis,Australia,24,5,807,42.5,833,96.9,1,5,...,34,953,22,944,157,6.05,43.3,Right-Handed,Medium,batsman-bowler
17,Usman Khawaja,Australia,20,2,583,32.4,725,80.4,0,5,...,8,0,0,0,0,0.00,0.0,Left-Handed,Medium,batsman

In [72]:
#4s by matches
foursbymat = matches_played['4s']/matches_played.Bat_Innings
foursbymat = foursbymat.sort_values(ascending = False).head(10)
matches_played.iloc[foursbymat.index]

,Player Name,Team,Bat_Innings,Not Outs,Runs,Bat_Avg,Balls Faced,Strike Rate,100s,50s,...,6s,Runs Given,wickets,Balls Bowled,overs bowled,Economy,Ball_Average,Bat_style,Bowl_Style,Primary
4,Shikhar Dhawan,India,122,7,5178,45.0,5539,93.5,15,27,...,64,0,0,0,0,0.00,0.0,Left-Handed,No,batsman
3,Virat Kohli,India,214,37,10533,59.5,11376,92.6,39,49,...,114,665,4,665,111,6.22,166.2,Right-Handed,Medium,batsman-bowler
6,Vijay Shankar,India,1,0,45,45.0,64,70.3,0,0,...,0,78,0,96,16,4.87,0.0,Right-Handed,Medium,batsman-bowler
15,Aaron Finch,Australia,95,1,3444,36.6,3871,89.0,11,18,...,76,137,2,158,26,5.20,68.5,Right-Handed,Leg Spin,batsman-bowler
14,Shaun Marsh,Australia,62,2,2536,42.3,5165,81.9,7,13,...,33,0,0,0,0,0.00,0.0,Left-Handed,Leg Spin,batsman
2,Rohit Sharma,India,195,31,7808,47.6,8840,88.3,22,39,...,215,515,8,593,99,5.21,64.4,Right-Handed,Off Spin,batsman-bowler
18,Glenn Maxwell,Australia,81,9,2327,32.3,1913,121.6,1,16,...,74,1885,46,2020,337,5.59,41.0,Right-Handed,Off Spin,batsman-bowler
1,MS Dhoni,India,286,81,10415,50.8,11877,87.7,10,70,...,222,0,0,0,0,0.00,0.0,Right-Handed,No,batsman
27,Alex Carey,Australia,9,9,246,27.3,322,76.4,0,0,...,2,0,0,0,0,0.00,0.0,Left-Handed,No,batsman
17,Usman Khawaja,Australia,20,2,583,32.4,725,80.4,0,5,...,8,0,0,0,0,0.00,0.0,Left-Handed,Medium,batsman

In [73]:
#maximum sixes

sixs = matches_played['6s'].sort_values(ascending = False).head(10)
matches_played.iloc[sixs.index]

,Player Name,Team,Bat_Innings,Not Outs,Runs,Bat_Avg,Balls Faced,Strike Rate,100s,50s,...,6s,Runs Given,wickets,Balls Bowled,overs bowled,Economy,Ball_Average,Bat_style,Bowl_Style,Primary
1,MS Dhoni,India,286,81,10415,50.8,11877,87.7,10,70,...,222,0,0,0,0,0.00,0.0,Right-Handed,No,batsman
2,Rohit Sharma,India,195,31,7808,47.6,8840,88.3,22,39,...,215,515,8,593,99,5.21,64.4,Right-Handed,Off Spin,batsman-bowler
3,Virat Kohli,India,214,37,10533,59.5,11376,92.6,39,49,...,114,665,4,665,111,6.22,166.2,Right-Handed,Medium,batsman-bowler
15,Aaron Finch,Australia,95,1,3444,36.6,3871,89.0,11,18,...,76,137,2,158,26,5.20,68.5,Right-Handed,Leg Spin,batsman-bowler
18,Glenn Maxwell,Australia,81,9,2327,32.3,1913,121.6,1,16,...,74,1885,46,2020,337,5.59,41.0,Right-Handed,Off Spin,batsman-bowler
4,Shikhar Dhawan,India,122,7,5178,45.0,5539,93.5,15,27,...,64,0,0,0,0,0.00,0.0,Left-Handed,No,batsman
26,Marcus Stoinis,Australia,24,5,807,42.5,833,96.9,1,5,...,34,953,22,944,157,6.05,43.3,Right-Handed,Medium,batsman-bowler
14,Shaun Marsh,Australia,62,2,2536,42.3,5165,81.9,7,13,...,33,0,0,0,0,0.00,0.0,Left-Handed,Leg Spin,batsman
0,Dinesh Karthik,India,77,21,1738,31.0,2358,73.7,0,9,...,15,0,0,0,0,0.00,0.0,Right-Handed,No,batsman
17,Usman Khawaja,Australia,20,2,583,32.4,725,80.4,0,5,...,8,0,0,0,0,0.00,0.0,Left-Handed,Medium,batsman

In [77]:
#maximum sixs by matches

sixsbymat = matches_played[matches_played['Bat_Innings'] >= 50]['6s']/matches_played[matches_played['Bat_Innings'] >= 50].Bat_Innings
sixsbymat = sixsbymat.sort_values(ascending = False).head(10)
matches_played.iloc[sixsbymat.index]

,Player Name,Team,Bat_Innings,Not Outs,Runs,Bat_Avg,Balls Faced,Strike Rate,100s,50s,...,6s,Runs Given,wickets,Balls Bowled,overs bowled,Economy,Ball_Average,Bat_style,Bowl_Style,Primary
26,Marcus Stoinis,Australia,24,5,807,42.5,833,96.9,1,5,...,34,953,22,944,157,6.05,43.3,Right-Handed,Medium,batsman-bowler
2,Rohit Sharma,India,195,31,7808,47.6,8840,88.3,22,39,...,215,515,8,593,99,5.21,64.4,Right-Handed,Off Spin,batsman-bowler
18,Glenn Maxwell,Australia,81,9,2327,32.3,1913,121.6,1,16,...,74,1885,46,2020,337,5.59,41.0,Right-Handed,Off Spin,batsman-bowler
15,Aaron Finch,Australia,95,1,3444,36.6,3871,89.0,11,18,...,76,137,2,158,26,5.20,68.5,Right-Handed,Leg Spin,batsman-bowler
1,MS Dhoni,India,286,81,10415,50.8,11877,87.7,10,70,...,222,0,0,0,0,0.00,0.0,Right-Handed,No,batsman
3,Virat Kohli,India,214,37,10533,59.5,11376,92.6,39,49,...,114,665,4,665,111,6.22,166.2,Right-Handed,Medium,batsman-bowler
14,Shaun Marsh,Australia,62,2,2536,42.3,5165,81.9,7,13,...,33,0,0,0,0,0.00,0.0,Left-Handed,Leg Spin,batsman
4,Shikhar Dhawan,India,122,7,5178,45.0,5539,93.5,15,27,...,64,0,0,0,0,0.00,0.0,Left-Handed,No,batsman
8,Rishabh Pant,India,2,0,41,20.5,31,132.2,0,0,...,1,0,0,0,0,0.00,0.0,Left-Handed,No,batsman
7,Lokesh Rahul,India,12,3,317,35.2,393,80.7,1,2,...,5,0,0,0,0,0.00,0.0,Right-Handed,No,batsman

# The Out Come of the Series will be 5-0 where india will win all the match

#India will win the series

#Top 3 Highest Run scorer 
Virat Kohli(By runs and matches)
Shikhar Dhawan(By runs and matches)
Glenn Maxwell(By strike rate)

#Top 3 Highest Wicket-Taker
Jasprit Bumrah (By matches)
Umesh Yadav (By only wickets)
Yuzvendra Chahal(By wickets and matches)

#Highest 4s
Shikhar Dhawan(By 4s/matches)
Virat Kohli(By only 4s)

#Highest 6s
Rohit Sharma(By 6s/matches)
MS Dhoni(By only 6s)